enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@3":
    dependencies:
      typescript: ^4.4.4

yarnPath: .yarn/releases/yarn-3.1.1.cjs
